# Generated by Django 4.2.6 on 2023-10-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=256, verbose_name='Логин')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('pas', models.CharField(max_length=256, verbose_name='Пароль')),
            ],
        ),
    ]
