# Generated by Django 4.2.6 on 2023-10-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.IntegerField(max_length=256, verbose_name='Номер')),
                ('date_bron', models.DateField(verbose_name='Дата бронирования')),
                ('date_zaezda', models.DateField(verbose_name='Дата заезда')),
                ('date_viezda', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(max_length=256, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
