# Generated by Django 4.2.6 on 2023-10-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_category_numbers_delete_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='date_bron',
            field=models.DateField(blank=True, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='date_viezda',
            field=models.DateField(blank=True, verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='date_zaezda',
            field=models.DateField(blank=True, verbose_name='Дата заезда'),
        ),
    ]
