# Generated by Django 4.2.6 on 2023-11-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_cart_total_price_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pict',
            field=models.ImageField(blank=True, null=True, upload_to='static/image'),
        ),
    ]
