# Generated by Django 4.2.7 on 2023-11-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/avatars/'),
        ),
    ]
