# Generated by Django 4.2.7 on 2023-11-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_remove_profile_photo_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='images/avatars/'),
        ),
    ]
