# Generated by Django 4.2.7 on 2023-11-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pict',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
